// requires impact.base.image.d.ts
// requires impact.base.event.d.ts
// requires impact.feature.gui.gui.d.ts
// requires impact.feature.gui.base.basic-gui.d.ts
// requires impact.feature.interact.button-interact.d.ts
// requires game.feature.control.control.d.ts
// requires game.feature.gui.base.button.d.ts
// requires game.feature.gui.base.boxes.d.ts
// requires game.feature.gui.base.numbers.d.ts
// requires game.feature.menu.gui.menu-misc.d.ts
