// requires game.loader.d.ts
// requires game.constants.d.ts
// requires impact.feature.database.plug-in.d.ts
// requires impact.feature.gamepad.plug-in.d.ts
// requires impact.feature.base.plug-in.d.ts
// requires impact.feature.bgm.plug-in.d.ts
// requires impact.feature.event-sheet.plug-in.d.ts
// requires impact.feature.camera.plug-in.d.ts
// requires impact.feature.rumble.plug-in.d.ts
// requires impact.feature.slow-motion.plug-in.d.ts
// requires impact.feature.effect.plug-in.d.ts
// requires impact.feature.gui.plug-in.d.ts
// requires impact.feature.light.plug-in.d.ts
// requires impact.feature.height-map.plug-in.d.ts
// requires impact.feature.navigation.plug-in.d.ts
// requires impact.feature.map-content.plug-in.d.ts
// requires impact.feature.map-image.plug-in.d.ts
// requires impact.feature.overlay.plug-in.d.ts
// requires impact.feature.dream-fx.plug-in.d.ts
// requires impact.feature.parallax.plug-in.d.ts
// requires impact.feature.screen-blur.plug-in.d.ts
// requires impact.feature.terrain.plug-in.d.ts
// requires impact.feature.interact.plug-in.d.ts
// requires impact.feature.env-particles.plug-in.d.ts
// requires impact.feature.storage.plug-in.d.ts
// requires impact.feature.weather.plug-in.d.ts
// requires impact.feature.map-sounds.plug-in.d.ts
// requires impact.feature.nwf.plug-in.d.ts
// requires impact.feature.video.plug-in.d.ts
// requires impact.feature.influencer.plug-in.d.ts
// requires impact.feature.greenworks.plug-in.d.ts
// requires game.feature.version.plug-in.d.ts
// requires game.feature.timers.plug-in.d.ts
// requires game.feature.achievements.plug-in.d.ts
// requires game.feature.auto-control.plug-in.d.ts
// requires game.feature.inventory.plug-in.d.ts
// requires game.feature.font.font-system.d.ts
// requires game.feature.ar.plug-in.d.ts
// requires game.feature.base.plug-in.d.ts
// requires game.feature.bgm.plug-in.d.ts
// requires game.feature.character.plug-in.d.ts
// requires game.feature.combat.plug-in.d.ts
// requires game.feature.game-code.plug-in.d.ts
// requires game.feature.gui.plug-in.d.ts
// requires game.feature.map-content.plug-in.d.ts
// requires game.feature.model.plug-in.d.ts
// requires game.feature.skills.plug-in.d.ts
// requires game.feature.msg.plug-in.d.ts
// requires game.feature.interact.plug-in.d.ts
// requires game.feature.npc.plug-in.d.ts
// requires game.feature.player.plug-in.d.ts
// requires game.feature.puzzle.plug-in.d.ts
// requires game.feature.control.control.d.ts
// requires game.feature.menu.plug-in.d.ts
// requires game.feature.quick-menu.plug-in.d.ts
// requires game.feature.tutorial.plug-in.d.ts
// requires game.feature.trade.plug-in.d.ts
// requires game.feature.save-preset.plug-in.d.ts
// requires game.feature.xeno-dialogs.plug-in.d.ts
// requires game.feature.quest.plug-in.d.ts
// requires game.feature.party.plug-in.d.ts
// requires game.feature.common-event.plug-in.d.ts
// requires game.feature.voice-acting.plug-in.d.ts
// requires game.feature.credits.plug-in.d.ts
// requires game.feature.arena.plug-in.d.ts
// requires game.feature.new-game.plug-in.d.ts
// requires game.feature.game-sense.plug-in.d.ts
