// requires game.feature.menu.area-loadable
// requires game.feature.menu.menu-steps
// requires game.feature.menu.gui.menu-misc
// requires game.feature.menu.gui.base-menu
// requires game.feature.menu.gui.main-menu
// requires game.feature.menu.gui.start-menu
// requires game.feature.menu.gui.equip.equip-menu
// requires game.feature.menu.gui.list-boxes
// requires game.feature.menu.gui.circuit.circuit-menu
// requires game.feature.menu.gui.circuit.circuit-misc
// requires game.feature.menu.gui.item.item-menu
// requires game.feature.menu.gui.map.map-menu
// requires game.feature.menu.gui.social.social-menu
// requires game.feature.menu.gui.save.save-menu
// requires game.feature.menu.gui.options.options-menu
// requires game.feature.menu.gui.shop.shop-menu
// requires game.feature.menu.gui.synop.synop-menu
// requires game.feature.menu.gui.quests.quest-menu
// requires game.feature.menu.gui.quest-hub.quest-hub-menu
// requires game.feature.menu.gui.enemies.enemy-menu
// requires game.feature.menu.gui.lore.lore-menu
// requires game.feature.menu.gui.help.help-menu
// requires game.feature.menu.gui.status.status-menu
// requires game.feature.menu.gui.museum.museum-menu
// requires game.feature.menu.gui.stats.stats-menu
// requires game.feature.menu.gui.trophy.trophy-menu
// requires game.feature.menu.gui.trade.trader-menu
// requires game.feature.menu.gui.botanics.botanics-menu
// requires game.feature.menu.gui.arena.arena-menu
// requires game.feature.menu.gui.new-game.new-game-menu
// requires game.feature.menu.menu-model
// requires game.feature.menu.lore-model
