// requires game.feature.map-content.entities.elevator.d.ts
// requires game.feature.map-content.map-content-steps.d.ts
// requires game.feature.map-content.gui.icon-hover-text.d.ts
// requires game.feature.map-content.map-style.d.ts
// requires game.feature.map-content.sc-doors.d.ts
// requires game.feature.map-content.prop-interact.d.ts
// requires game.feature.map-content.entities.jump-panel.d.ts
// requires game.feature.map-content.entities.teleport-central.d.ts
// requires game.feature.map-content.entities.rhombus-point.d.ts
