// requires impact.base.game

export {};

declare global {
	namespace sc {
		namespace Modifiers {
			interface Modifier {
				icon: number
				order?: number
				noPercent?: boolean
				altSheet?: string
				offX?: number
				offY?: number
			}

			enum KnownModifiers {
				AIM_SPEED = "AIM_SPEED",
				AIM_STABILITY = "AIM_STABILITY",
				AIMING_MOVEMENT = "AIMING_MOVEMENT",
				KNOCKBACK = "KNOCKBACK",
				RANGED_DMG = "RANGED_DMG",
				MELEE_DMG = "MELEE_DMG",
				CRITICAL_DMG = "CRITICAL_DMG",
				BREAK_DMG = "BREAK_DMG",
				SPIKE_DMG = "SPIKE_DMG",
				ASSAULT = "ASSAULT",
				CROSS_COUNTER = "CROSS_COUNTER",
				BERSERK = "BERSERK",
				MOMENTUM = "MOMENTUM",
				DASH_INVINC = "DASH_INVINC",
				DASH_STEP = "DASH_STEP",
				GUARD_STRENGTH = "GUARD_STRENGTH",
				GUARD_SP = "GUARD_SP",
				GUARD_AREA = "GUARD_AREA",
				PERFECT_GUARD_WINDOW = "PERFECT_GUARD_WINDOW",
				PERFECT_GUARD_RESET = "PERFECT_GUARD_RESET",
				STUN_THRESHOLD = "STUN_THRESHOLD",
				OVERHEAT_REDUCTION = "OVERHEAT_REDUCTION",
				HP_REGEN = "HP_REGEN",
				SP_REGEN = "SP_REGEN",
				ITEM_GUARD = "ITEM_GUARD",
				ONCE_MORE = "ONCE_MORE",
				XP_PLUS = "XP_PLUS",
				DROP_CHANCE = "DROP_CHANCE",
				MONEY_PLUS = "MONEY_PLUS",
				XP_ZERO = "XP_ZERO",
				RANK_PLANTS = "RANK_PLANTS",
				ITEM_BOOST = "ITEM_BOOST",
				APPETITE = "APPETITE",
				COND_HEALING = "COND_HEALING",
				COND_EFFECT_HEAT = "COND_EFFECT_HEAT",
				COND_EFFECT_COLD = "COND_EFFECT_COLD",
				COND_EFFECT_SHOCK = "COND_EFFECT_SHOCK",
				COND_EFFECT_WAVE = "COND_EFFECT_WAVE",
				COND_EFFECT_ALL = "COND_EFFECT_ALL",
				COND_GUARD_HEAT = "COND_GUARD_HEAT",
				COND_GUARD_COLD = "COND_GUARD_COLD",
				COND_GUARD_SHOCK = "COND_GUARD_SHOCK",
				COND_GUARD_WAVE = "COND_GUARD_WAVE",
				SPIDER_SLOW_DOWN_GUARD = "SPIDER_SLOW_DOWN_GUARD",
				BEGONE_ICE = "BEGONE_ICE",
			}
		}

		var MODIFIERS: Record<string, sc.Modifiers.Modifier>
	}
}