// requires game.feature.puzzle.components.push-pullable
// requires game.feature.puzzle.entities.block
// requires game.feature.puzzle.entities.blockers
// requires game.feature.puzzle.entities.bomb
// requires game.feature.puzzle.entities.water-bubble
// requires game.feature.puzzle.entities.compressor
// requires game.feature.puzzle.entities.water-block
// requires game.feature.puzzle.entities.ice-disk
// requires game.feature.puzzle.entities.key-panel
// requires game.feature.puzzle.entities.ball-changer
// requires game.feature.puzzle.entities.walls
// requires game.feature.puzzle.entities.glowing-line
// requires game.feature.puzzle.entities.lorry
// requires game.feature.puzzle.entities.ferro
// requires game.feature.puzzle.entities.one-time-switch
// requires game.feature.puzzle.entities.element-shield
// requires game.feature.puzzle.entities.floor-switch
// requires game.feature.puzzle.entities.magnet
// requires game.feature.puzzle.entities.multi-hit-switch
// requires game.feature.puzzle.entities.bounce-switch
// requires game.feature.puzzle.entities.thermo-pole
// requires game.feature.puzzle.entities.push-pull-block
// requires game.feature.puzzle.entities.push-pull-dest
// requires game.feature.puzzle.entities.sliding-block
// requires game.feature.puzzle.entities.switch
// requires game.feature.puzzle.entities.destructible
// requires game.feature.puzzle.entities.item-destruct
// requires game.feature.puzzle.entities.regen-destruct
// requires game.feature.puzzle.entities.extract-platform
// requires game.feature.puzzle.entities.dynamic-platform
// requires game.feature.puzzle.entities.ol-platform
// requires game.feature.puzzle.entities.enemy-counter
// requires game.feature.puzzle.entities.group-switch
// requires game.feature.puzzle.entities.chest
// requires game.feature.puzzle.entities.quick-sand
// requires game.feature.puzzle.entities.spiderweb
// requires game.feature.puzzle.entities.steam-pipes
// requires game.feature.puzzle.entities.tesla-coil
// requires game.feature.puzzle.entities.wave-teleport
// requires game.feature.puzzle.puzzle-steps
// requires game.feature.puzzle.entities.rotate-blocker
// requires game.feature.puzzle.entities.boss-platform
