// requires impact.feature.gui.gui
// requires impact.feature.gui.base.basic-gui
// requires game.feature.menu.gui.base-menu
// requires game.feature.menu.gui.menu-misc
// requires game.feature.menu.gui.item.item-status-default
// requires game.feature.menu.gui.status.status-misc
// requires game.feature.menu.gui.status.status-view-main
// requires game.feature.menu.gui.status.status-view-parameters
// requires game.feature.menu.gui.status.status-view-modifiers
// requires game.feature.menu.gui.status.status-view-combat-arts
