// requires impact.feature.rumble.rumble
// requires impact.feature.gui.gui
// requires impact.feature.gui.base.basic-gui
// requires impact.feature.gui.base.box
// requires game.feature.gui.base.boxes
// requires game.feature.arena.arena
// requires game.feature.gui.hud.right-hud
// requires game.feature.gui.base.text
// requires game.feature.menu.gui.menu-misc
// requires game.feature.menu.gui.arena.arena-misc
// requires game.feature.arena.gui.arena-effect-display
// requires game.feature.arena.gui.arena-round-gui
// requires game.feature.arena.gui.arena-trophy-gui
// requires game.feature.arena.gui.arena-rush-gui
