// requires impact.feature.rumble.rumble.d.ts
// requires impact.feature.gui.gui.d.ts
// requires impact.feature.gui.base.basic-gui.d.ts
// requires impact.feature.gui.base.box.d.ts
// requires game.feature.gui.base.boxes.d.ts
// requires game.feature.arena.arena.d.ts
// requires game.feature.gui.hud.right-hud.d.ts
// requires game.feature.gui.base.text.d.ts
// requires game.feature.menu.gui.menu-misc.d.ts
// requires game.feature.menu.gui.arena.arena-misc.d.ts
// requires game.feature.arena.gui.arena-effect-display.d.ts
// requires game.feature.arena.gui.arena-round-gui.d.ts
// requires game.feature.arena.gui.arena-trophy-gui.d.ts
// requires game.feature.arena.gui.arena-rush-gui.d.ts
