// requires game.feature.puzzle.components.push-pullable.d.ts
// requires game.feature.puzzle.entities.block.d.ts
// requires game.feature.puzzle.entities.blockers.d.ts
// requires game.feature.puzzle.entities.bomb.d.ts
// requires game.feature.puzzle.entities.water-bubble.d.ts
// requires game.feature.puzzle.entities.compressor.d.ts
// requires game.feature.puzzle.entities.water-block.d.ts
// requires game.feature.puzzle.entities.ice-disk.d.ts
// requires game.feature.puzzle.entities.key-panel.d.ts
// requires game.feature.puzzle.entities.ball-changer.d.ts
// requires game.feature.puzzle.entities.walls.d.ts
// requires game.feature.puzzle.entities.glowing-line.d.ts
// requires game.feature.puzzle.entities.lorry.d.ts
// requires game.feature.puzzle.entities.one-time-switch.d.ts
// requires game.feature.puzzle.entities.element-shield.d.ts
// requires game.feature.puzzle.entities.floor-switch.d.ts
// requires game.feature.puzzle.entities.magnet.d.ts
// requires game.feature.puzzle.entities.multi-hit-switch.d.ts
// requires game.feature.puzzle.entities.bounce-switch.d.ts
// requires game.feature.puzzle.entities.thermo-pole.d.ts
// requires game.feature.puzzle.entities.push-pull-block.d.ts
// requires game.feature.puzzle.entities.push-pull-dest.d.ts
// requires game.feature.puzzle.entities.sliding-block.d.ts
// requires game.feature.puzzle.entities.switch.d.ts
// requires game.feature.puzzle.entities.destructible.d.ts
// requires game.feature.puzzle.entities.item-destruct.d.ts
// requires game.feature.puzzle.entities.regen-destruct.d.ts
// requires game.feature.puzzle.entities.extract-platform.d.ts
// requires game.feature.puzzle.entities.dynamic-platform.d.ts
// requires game.feature.puzzle.entities.ol-platform.d.ts
// requires game.feature.puzzle.entities.enemy-counter.d.ts
// requires game.feature.puzzle.entities.group-switch.d.ts
// requires game.feature.puzzle.entities.chest.d.ts
// requires game.feature.puzzle.entities.quick-sand.d.ts
// requires game.feature.puzzle.entities.spiderweb.d.ts
// requires game.feature.puzzle.entities.steam-pipes.d.ts
// requires game.feature.puzzle.entities.tesla-coil.d.ts
// requires game.feature.puzzle.entities.wave-teleport.d.ts
// requires game.feature.puzzle.puzzle-steps.d.ts
// requires game.feature.puzzle.entities.rotate-blocker.d.ts
// requires game.feature.puzzle.entities.boss-platform.d.ts
