// requires impact.feature.gui.gui.d.ts
// requires impact.feature.gui.base.basic-gui.d.ts
// requires game.feature.menu.gui.base-menu.d.ts
// requires game.feature.menu.gui.menu-misc.d.ts
// requires game.feature.menu.gui.item.item-status-default.d.ts
// requires game.feature.menu.gui.status.status-misc.d.ts
// requires game.feature.menu.gui.status.status-view-main.d.ts
// requires game.feature.menu.gui.status.status-view-parameters.d.ts
// requires game.feature.menu.gui.status.status-view-modifiers.d.ts
// requires game.feature.menu.gui.status.status-view-combat-arts.d.ts
