// requires game.feature.combat.combat
// requires game.feature.combat.pvp
// requires game.feature.combat.combat-shield
// requires game.feature.combat.combat-force
// requires game.feature.combat.combat-stun
// requires game.feature.combat.combat-assault
// requires game.feature.combat.combat-poi
// requires game.feature.combat.combat-charge
// requires game.feature.combat.combat-sweep
// requires game.feature.combat.stat-change
// requires game.feature.combat.entities.combatant-marble
// requires game.feature.combat.entities.ball
// requires game.feature.combat.entities.combatant
// requires game.feature.combat.entities.food-icon
// requires game.feature.combat.entities.drop
// requires game.feature.combat.entities.item-drop
// requires game.feature.combat.entities.enemy
// requires game.feature.combat.entities.enemy-spawner
// requires game.feature.combat.entities.respawn-blocker
// requires game.feature.combat.entities.hit-number
// requires game.feature.combat.entities.burst-spawner
// requires game.feature.combat.entities.stone
// requires game.feature.combat.gui.status-bar
// requires game.feature.combat.gui.pvp-gui
// requires game.feature.combat.gui.hp-bar-boss
// requires game.feature.combat.gui.enemy-display-gui
// requires game.feature.combat.model.combat-condition
// requires game.feature.combat.model.combat-params
// requires game.feature.combat.model.combat-status
// requires game.feature.combat.model.enemy-type
// requires game.feature.combat.model.enemy-reaction
// requires game.feature.combat.model.enemy-collab
// requires game.feature.combat.model.enemy-level-scaling
// requires game.feature.combat.model.enemy-tracker
// requires game.feature.combat.model.enemy-booster
// requires game.feature.combat.combat-action-steps
// requires game.feature.combat.combat-event-steps
// requires game.feature.combat.enemy-steps
