// requires impact.feature.map-content.map-style
// requires impact.feature.map-content.entities.door
// requires impact.feature.map-content.entities.stair-door
// requires impact.feature.map-content.entities.teleport-ground
// requires impact.feature.map-content.entities.glowing-ground
// requires impact.feature.map-content.entities.prop
// requires impact.feature.map-content.entities.scalable-prop
// requires impact.feature.map-content.entities.hidden-block
// requires impact.feature.map-content.entities.note
// requires impact.feature.map-content.map-content-steps
