// requires impact.feature.effect.entities.effect-previewer
// requires impact.feature.effect.effect-sheet
// requires impact.feature.effect.effect-steps
// requires impact.feature.effect.fx.fx-basic
// requires impact.feature.effect.fx.fx-box
// requires impact.feature.effect.fx.fx-color
// requires impact.feature.effect.fx.fx-circle
// requires impact.feature.effect.fx.fx-homing
// requires impact.feature.effect.fx.fx-light
// requires impact.feature.effect.fx.fx-line
// requires impact.feature.effect.fx.fx-rhombus
// requires impact.feature.effect.fx.fx-wipe
