extends: eslint-config-dmitmel/presets/node
env:
  browser: true

rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport

overrides:
  - files: '**/*.ts'
    extends:
      - eslint-config-dmitmel/presets/typescript-addon
      # - eslint-config-dmitmel/presets/typescript-with-type-checking-addon
    parserOptions:
      project: 'tsconfig.json'

  - files: '**/*.d.ts'
    rules:
      # `declare var` implicitly creates a property on the `Window` object
      no-var: off
      '@typescript-eslint/no-empty-interface': off
      '@typescript-eslint/no-explicit-any':
        - warn
        - ignoreRestArgs: true

      # everything in declarations is public anyway
      '@typescript-eslint/explicit-member-accessibility':
        - warn
        - accessibility: no-public

      node/no-missing-import: off
      node/no-extraneous-import: off

      # See <https://github.com/typescript-eslint/typescript-eslint/pull/2902>
      # and <https://github.com/typescript-eslint/typescript-eslint/pull/2902>
      '@typescript-eslint/no-unused-vars': off
